### ISSUE TITLE
Month view in DatePicker does not change on date change.

### ISSUE THREAD

**Issue by MihaelBercic** [probablykasper/date-picker-svelte#37]
If the date that is bound is changed from another source, the month (and maybe year) does not change according to the change that happened to the date.

Month stays the same.

**Comment by probablykasper** [comment]
Should be fixed in `v2.5.5`, thanks for the report!

**Comment by MihaelBercic** [comment]
> Should be fixed in `v2.5.5`, thanks for the report!

Did you mean `v2.2.5` by any chance? If so, do you have any ETA on when it will be released?

Appreciate the work <3

**Comment by probablykasper** [comment]
Yes, `v2.2.5`. It's already out, just forgot to create the GitHub release

**Comment by FearsomeFlyingJacob** [comment]
This is still happening to me in `v2.10.0`, I'm using a `writable` date and changing it in another place, the date picker stays on the same view and doesn't update to show the new date.

**Comment by probablykasper** [comment]
@FearsomeFlyingJacob Please provide a REPL

**Comment by FearsomeFlyingJacob** [comment]
Here is the REPL: https://svelte.dev/repl/b7f78a985fe44f0cbb136eea6d86383a?version=4.2.8

The two date pickers start with 2021-01-01 and today as selected dates.
Clicking the "last xyz" buttons correctly update the selection in the stores and in the date pickers, but the date pickers don't change view to show the currently selected date.

**Comment by probablykasper** [comment]
Fixed in v2.10.1
